name: Prod release build

on:
  push:
    branches: [ build*, build/*, release*, release/* ]
  pull_request:
    branches: [ build*, build/*, release*, release/* ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Unit test with Gradle
        run: ./gradlew testMockDebug --stacktrace


  buildartifact:
    runs-on: ubuntu-latest
    needs:
      - unittest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Getting config for signing and build
        env:
          releaseKeyPass: ${{ secrets.PROD_KEY_PASS }}
          encodedCert: ${{ secrets.PROD_CERT_GPG }}
          decodePass: ${{ secrets.PROD_CERT_GPG_PASS }}
        run: |
          echo 'Starting fetch cert'
          echo "${{ secrets.PROD_CERT_GPG }}" > nomadProd.keystore.asc
          gpg -d --passphrase "${{ secrets.PROD_CERT_GPG_PASS }}" --batch nomadProd.keystore.asc > app/nomadProd.keystore
          echo 'Save done'
          ./gradlew assembleProdRelease
          echo 'Build done'
      - uses: actions/upload-artifact@v2
        with:
          name: built-artifact
          path: app/build/outputs/apk/prod/

